services:
  mysql:
    image: mysql:8.0
    container_name: rbac-mysql
    environment:
      MYSQL_DATABASE: rbac
      MYSQL_USER: myuser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: verysecret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7.4
    container_name: rbac-redis
    ports:
      - "6379:6379"

volumes:
  mysql_data:
